build site:
  only:
    - merge_requests
  image: node:latest
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - ./build
cache:
  paths:
    - node_modules/

deploy:
  only:
    - merge_requests
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete build/ pettegre@it2810-40.idi.ntnu.no:/var/www/html/prosjekt3/
    - ssh pettegre@it2810-40.idi.ntnu.no 'mkdir /var/www/html/prosjekt3/images && cp -R /images-prosjekt3/* /var/www/html/prosjekt3/images'
